20240112

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,10 +38,19 @@ jobs:
       
     - name: Fetch previous data
       run: |
+        set +e  # 禁用錯誤退出碼
         git config pull.rebase true
         git config merge.ours.driver true
-        git rebase --abort >>/dev/null
-        git merge -X ours origin/main
+        git pull origin main
+        EXIT_CODE=$?
+      
+        if [ $EXIT_CODE -ne 0 ]; then
+          echo "Failed to pull, switch to other method"
+          git rebase --abort
+          git merge -X ours origin/main
+        fi
+      
+        set -e  # 启用错误退出码
         
         
     
